import HwNavBar from "components/HwNavBar";
import Head from "next/head";
import Image from "next/image";
import DatePicker from 'tailwind-datepicker-react'
import { useEffect, useState } from "react";
import axios from "axios";

const Dashboard = () => { 
    const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL
    let currentDate = new Date()
    currentDate.setHours(0, 0, 0, 0)
    const [startDate, setStartDate] = useState<Date>(currentDate)
    const [endDate, setEndDate] = useState<Date>(currentDate)
    const [anchorDate, setAnchorDate] = useState<Date>(currentDate)

    const [showStartDatePicker, setShowStartDatePicker] = useState<boolean>(false)
    const [showEndDatePicker, setShowEndDatePicker] = useState<boolean>(false)
    const [showAnchorDatePicker, setShowAnchorDatePicker] = useState<boolean>(false)

    const [endDateInvalid, setEndDateInvalid] = useState<boolean>(false)

    useEffect(() => {
        console.log("startDate: ", startDate)
        console.log("endDate: ", endDate)
        console.log("anchorDate: ", anchorDate)
        if (!startDate || !endDate || !anchorDate || endDate < startDate || anchorDate > startDate ) {
            console.log("Selected Dates are Invalid")
            setEndDateInvalid(true)
        } else {
            setEndDateInvalid(false)
        }
    }, [endDate, startDate, anchorDate])

    const datepickerOptions = {
        title: "",
        autoHide: false,
        todayBtn: true,
        clearBtn: true,
        theme: {
            background: endDateInvalid ? "bg-red-500" : "bg-white",
            todayBtn: "",
            clearBtn: "",
            icons: "",
            text: "",
            disabledText: "",
            input: "bg-white",
            inputIcon: "",
            selected: "",
        },
        datepickerClassNames: "top-12",
        language: "en",
    }

    const handleSearch = () => {
        const month_year_day = anchorDate.toLocaleString('default', { month: '2-digit', day: '2-digit', year: 'numeric' }).split('/')
        const anchor =  month_year_day[2] + '-' + month_year_day[0] + '-' + month_year_day[1]
        const work_days = startDate.getDate() - anchorDate.getDate()
        const vacation_days = endDate.getDate() - startDate.getDate() + 1
        
        const destination = `${BACKEND_URL}/setcalendar?anchor=${anchor}&work_days=${work_days}&vacation_days=${vacation_days}`
        console.log(`Sending request to ${destination}`)
        axios.post(destination).then((res) => {
            console.log(res.data)
        })
        .catch((err) => {
            console.log(err)
        })
    }

    return (
        <>
            <Head>
                <title>Vacation Planner</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col items-center w-full min-h-screen">
                <HwNavBar />
                <Image src="/dalleImg.png" alt="hero" width={718} height={718} className="absolute blur-3xl scale-x-[2.3] scale-150 opacity-80" />
                <div className="relative mt-24 flex flex-col items-center">
                    <h2 className="text-3xl font-bold tracking-tight text-white-900 sm:text-4xl">
                        I want to take a vacation on
                    </h2>
                    <div className="flex flex-row gap-x-5 items-center mt-4">
                        <div>
                            <DatePicker
                                options={datepickerOptions}
                                value={startDate}
                                onChange={(date) => setStartDate(date)}
                                setShow={(value) => setShowStartDatePicker(value)}
                                show={showStartDatePicker}
                            />
                        </div>
                        <h2 className="text-lg font-bold tracking-tight text-white-900 sm:text-2xl">
                            to
                        </h2>
                        <div>
                            <DatePicker
                                options={datepickerOptions}
                                value={endDate}
                                onChange={(date) => setEndDate(date)}
                                setShow={(value) => setShowEndDatePicker(value)}
                                show={showEndDatePicker}
                            />
                        </div>
                    </div>
                    <div className="flex flex-col items-center mt-5">
                        <h2 className="text-lg font-bold tracking-tight text-white-900 sm:text-xl">
                            And I want to start doing extra work on 
                        </h2>
                        <div className="mt-2">
                            {/* anchor date picker */}
                            <DatePicker
                                options={datepickerOptions}
                                value={anchorDate}
                                onChange={(date) => setAnchorDate(date)}
                                setShow={(value) => setShowAnchorDatePicker(value)}
                                show={showAnchorDatePicker}
                            />
                        </div>
                    </div>
                    <button 
                        className={`rounded-md lg:px-5 lg:py-3 px-3.5 py-1.5 
                            text-base font-semibold leading-7 text-white shadow-sm
                            focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 
                            focus-visible:outline-white mt-4 ${endDateInvalid ? "cursor-not-allowed bg-red-500 border-white border " : " bg-darkBlue  hover:bg-lightBlue "}`}
                        onClick={() => {!endDateInvalid && handleSearch()}}
                    >
                        {endDateInvalid ? "Selected Dates are Invalid": "Calculate my work distribution"}
                    </button>
                </div>
            </main>
        </>
    );
    };


export default Dashboard;