import Head from 'next/head'
import Image from 'next/image'
import { Inter, Roboto } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HwNavBar from 'components/HwNavBar'
import CenteredHero from 'components/CenteredHero'
import DatePicker from 'tailwind-datepicker-react'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: '400'})

export default function Home() {
  const [showDatePicker, setShowDatePicker] = useState<boolean>(false)


  return (
    <>
      <Head>
        <title>Vacation Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center w-full min-h-screen">
        <HwNavBar />
        <div className="absolute inset-x-0 top-[-10rem] transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]">
        <svg
          className="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]"
          viewBox="0 0 1155 678"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)"
            fillOpacity=".3"
            d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
          />
          <defs>
            <linearGradient
              id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533"
              x1="1155.49"
              x2="-78.208"
              y1=".177"
              y2="474.645"
              gradientUnits="userSpaceOnUse"
            >
              <stop stopColor="#9089FC" />
              <stop offset={1} stopColor="#FF80B5" />
            </linearGradient>
          </defs>
        </svg>
        </div>
        <div className="relative mt-20 w-full lg:px-8 px-6">
          <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
            <div className='text-center mb-8'>
              <h1 className="text-4xl font-bold tracking-tight text-white-900 sm:text-6xl">
                Plan your vacation with ease
              </h1>
            </div>
            <DatePicker setShow={(state) => setShowDatePicker(state)} show={showDatePicker}/>
          </div>
        </div>
      </main>
    </>
  )
}
