import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
// import Image from 'next/image'
import { Inter, Roboto } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import HwNavBar from 'components/HwNavBar'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: '400'})

export default function Home() {

  return (
    <>
      <Head>
        <title>Vacation Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center w-full min-h-screen">
        <Image src="/dalleImg.png" alt="hero" width={718} height={718} className="absolute blur-lg w-screen h-screen overflow-hidden opacity-80" />
        <HwNavBar showSignIn={true}/>
        <div className="relative w-full lg:px-8 px-6">
          <div className="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
            <div className='text-center mb-8'>
              <h1 className="text-4xl font-bold tracking-tight text-white-900 sm:text-6xl">
                Plan your vacation stress-free.
              </h1>
              <h2 className='text-lg mt-4'>
                Let Plan2Chill schedule your homework so you can focus on relaxing.
              </h2>
            </div>
            <div className='flex justify-center flex-row gap-x-6'>
              <Link href="/dashboard" className="rounded-md bg-darkBlue lg:px-5 lg:py-3 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm hover:bg-lightBlue focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">
                Get Started
              </Link>
              <a href="https://www.google.com/search?q=why+am+i+always+so+sad" className="rounded-md bg-transparent border-darkBlue border lg:px-5 lg:py-3 px-3.5 py-1.5 text-base font-semibold leading-7 text-white shadow-sm hover:bg-lightBlue focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">
                I hate hackathon projects
              </a>
              
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
